services:
  spmonitor-ttyd:
    image: ghcr.io/thin-edge/spmonitor-ttyd:latest
    restart: unless-stopped
    # Still using host mode to make the web UI accessible on the host IP
    network_mode: "host"

    # Run as a non-root user (UID 1000 is standard for the first host user)
    user: "1000:1000"

    # We strip all kernel capabilities for maximum hardening
    cap_drop:
      - ALL
